### ISSUE TITLE
fixed some things in a fork, but seems you implemented some of them since then

### ISSUE THREAD

**Issue by talarari** [jf1603/hain-plugin-gitlab#1]
cool plugin! saved me the trouble of writing my own.
i forked the code to change/fix some issues , but it looks like you handled some of them in the mean while so a pull request would cause a non automatic merge.

issues i handled:
1. when there is no description shows the text  'null'
2. added message to open preferences if none were entered.
3. changing configs requires a reload, added a update handler to fix this.
4. added message to tell a user to check prefs on error (bad token for instance)
4.used promises (this is more of a coding style thing)

the fork is here: https://github.com/talarari/hain-plugin-gitlab

feel free to take the parts you think are good, would love to hear what you think

**Comment by tetsuo-repo** [comment]
Thanks for taking care of some of the issues. Didn't expect someone to get into development that early - otherwise I would have worked a bit more structured.

I'll look into the things you've done. #3 is definately something that is on my list.
